# Disable runner because GH hosts use DT_RUNPATH to relocate the libpython

name: Multi platform / version testing
on: push

jobs:
  build:
    name: Tox test

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        # Use deadsnakes action until https://github.com/actions/setup-python/issues/325 is fixed
        uses: deadsnakes/action@v3.0.1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrage core dependencies
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install Tox and any other packages
        run: pip install tox

      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py
